//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationWebApplication.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StudDetails", Namespace="http://schemas.datacontract.org/2004/07/RegistrationWcfService")]
    [System.SerializableAttribute()]
    public partial class StudDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CourseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailaddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SportsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StudaddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StudidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Course {
            get {
                return this.CourseField;
            }
            set {
                if ((object.ReferenceEquals(this.CourseField, value) != true)) {
                    this.CourseField = value;
                    this.RaisePropertyChanged("Course");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Emailaddress {
            get {
                return this.EmailaddressField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailaddressField, value) != true)) {
                    this.EmailaddressField = value;
                    this.RaisePropertyChanged("Emailaddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Firstname {
            get {
                return this.FirstnameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstnameField, value) != true)) {
                    this.FirstnameField = value;
                    this.RaisePropertyChanged("Firstname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((object.ReferenceEquals(this.GenderField, value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lastname {
            get {
                return this.LastnameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastnameField, value) != true)) {
                    this.LastnameField = value;
                    this.RaisePropertyChanged("Lastname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sports {
            get {
                return this.SportsField;
            }
            set {
                if ((object.ReferenceEquals(this.SportsField, value) != true)) {
                    this.SportsField = value;
                    this.RaisePropertyChanged("Sports");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Studaddress {
            get {
                return this.StudaddressField;
            }
            set {
                if ((object.ReferenceEquals(this.StudaddressField, value) != true)) {
                    this.StudaddressField = value;
                    this.RaisePropertyChanged("Studaddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Studid {
            get {
                return this.StudidField;
            }
            set {
                if ((this.StudidField.Equals(value) != true)) {
                    this.StudidField = value;
                    this.RaisePropertyChanged("Studid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertStudDetails", ReplyAction="http://tempuri.org/IService1/InsertStudDetailsResponse")]
        string InsertStudDetails(RegistrationWebApplication.ServiceReference1.StudDetails stud);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertStudDetails", ReplyAction="http://tempuri.org/IService1/InsertStudDetailsResponse")]
        System.Threading.Tasks.Task<string> InsertStudDetailsAsync(RegistrationWebApplication.ServiceReference1.StudDetails stud);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetStudDetails", ReplyAction="http://tempuri.org/IService1/GetStudDetailsResponse")]
        System.Data.DataSet GetStudDetails(RegistrationWebApplication.ServiceReference1.StudDetails stud);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetStudDetails", ReplyAction="http://tempuri.org/IService1/GetStudDetailsResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetStudDetailsAsync(RegistrationWebApplication.ServiceReference1.StudDetails stud);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/FetchUpdatedRecords", ReplyAction="http://tempuri.org/IService1/FetchUpdatedRecordsResponse")]
        System.Data.DataSet FetchUpdatedRecords(RegistrationWebApplication.ServiceReference1.StudDetails stud);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/FetchUpdatedRecords", ReplyAction="http://tempuri.org/IService1/FetchUpdatedRecordsResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> FetchUpdatedRecordsAsync(RegistrationWebApplication.ServiceReference1.StudDetails stud);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateStudDetails", ReplyAction="http://tempuri.org/IService1/UpdateStudDetailsResponse")]
        string UpdateStudDetails(RegistrationWebApplication.ServiceReference1.StudDetails stud);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateStudDetails", ReplyAction="http://tempuri.org/IService1/UpdateStudDetailsResponse")]
        System.Threading.Tasks.Task<string> UpdateStudDetailsAsync(RegistrationWebApplication.ServiceReference1.StudDetails stud);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteStudDetails", ReplyAction="http://tempuri.org/IService1/DeleteStudDetailsResponse")]
        bool DeleteStudDetails(RegistrationWebApplication.ServiceReference1.StudDetails stud);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteStudDetails", ReplyAction="http://tempuri.org/IService1/DeleteStudDetailsResponse")]
        System.Threading.Tasks.Task<bool> DeleteStudDetailsAsync(RegistrationWebApplication.ServiceReference1.StudDetails stud);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckLogin", ReplyAction="http://tempuri.org/IService1/CheckLoginResponse")]
        bool CheckLogin(RegistrationWebApplication.ServiceReference1.StudDetails stud);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckLogin", ReplyAction="http://tempuri.org/IService1/CheckLoginResponse")]
        System.Threading.Tasks.Task<bool> CheckLoginAsync(RegistrationWebApplication.ServiceReference1.StudDetails stud);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : RegistrationWebApplication.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<RegistrationWebApplication.ServiceReference1.IService1>, RegistrationWebApplication.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string InsertStudDetails(RegistrationWebApplication.ServiceReference1.StudDetails stud) {
            return base.Channel.InsertStudDetails(stud);
        }
        
        public System.Threading.Tasks.Task<string> InsertStudDetailsAsync(RegistrationWebApplication.ServiceReference1.StudDetails stud) {
            return base.Channel.InsertStudDetailsAsync(stud);
        }
        
        public System.Data.DataSet GetStudDetails(RegistrationWebApplication.ServiceReference1.StudDetails stud) {
            return base.Channel.GetStudDetails(stud);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetStudDetailsAsync(RegistrationWebApplication.ServiceReference1.StudDetails stud) {
            return base.Channel.GetStudDetailsAsync(stud);
        }
        
        public System.Data.DataSet FetchUpdatedRecords(RegistrationWebApplication.ServiceReference1.StudDetails stud) {
            return base.Channel.FetchUpdatedRecords(stud);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> FetchUpdatedRecordsAsync(RegistrationWebApplication.ServiceReference1.StudDetails stud) {
            return base.Channel.FetchUpdatedRecordsAsync(stud);
        }
        
        public string UpdateStudDetails(RegistrationWebApplication.ServiceReference1.StudDetails stud) {
            return base.Channel.UpdateStudDetails(stud);
        }
        
        public System.Threading.Tasks.Task<string> UpdateStudDetailsAsync(RegistrationWebApplication.ServiceReference1.StudDetails stud) {
            return base.Channel.UpdateStudDetailsAsync(stud);
        }
        
        public bool DeleteStudDetails(RegistrationWebApplication.ServiceReference1.StudDetails stud) {
            return base.Channel.DeleteStudDetails(stud);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteStudDetailsAsync(RegistrationWebApplication.ServiceReference1.StudDetails stud) {
            return base.Channel.DeleteStudDetailsAsync(stud);
        }
        
        public bool CheckLogin(RegistrationWebApplication.ServiceReference1.StudDetails stud) {
            return base.Channel.CheckLogin(stud);
        }
        
        public System.Threading.Tasks.Task<bool> CheckLoginAsync(RegistrationWebApplication.ServiceReference1.StudDetails stud) {
            return base.Channel.CheckLoginAsync(stud);
        }
    }
}
